// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk3pbbdCo7bUYykjEBQ7zbzylsDa1A2iE',
    appId: '1:413861787586:android:7bc0d2307028e55c85485b',
    messagingSenderId: '413861787586',
    projectId: 'bravoo-481013',
    storageBucket: 'bravoo-481013.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTRRZz_e4QPOdSnzgbA1gVn9uc1T83s24',
    appId: '1:413861787586:ios:54a7c35279aa6f7585485b',
    messagingSenderId: '413861787586',
    projectId: 'bravoo-481013',
    storageBucket: 'bravoo-481013.firebasestorage.app',
    androidClientId: '413861787586-6fgh6he5n4p1v10c1l4osmc9iekck6fk.apps.googleusercontent.com',
    iosClientId: '413861787586-g0lkbu9m7nll0mrvm077fs15o9r0aq4q.apps.googleusercontent.com',
    iosBundleId: 'com.flowvahub.bravoo',
  );

}